#cloud-config

packages:
 - git-core

write_files:
 - content: |
    {
        "alertlogic": {
            "log-agent": {
                "provision_key": "0123456789abcdefghijklmnopqrstuvwxyz0123456789abcd"
            }
        },
        "run_list": "recipe[al_agents::log_agent]"
    }
   path: /etc/chef/node.json
   permissions: '0600'
 - content: |
    cookbook_path  "/tmp/cookbooks/"
    log_level      :info
    solo           true
   path: /etc/chef/solo.rb

runcmd:
 - curl -L https://www.opscode.com/chef/install.sh | bash
 - mkdir -p /tmp/cookbooks/
 - git clone --depth 1 https://github.com/alertlogic/al_agents.git /tmp/cookbooks/al_agents/
 - chef-solo -c /etc/chef/solo.rb -j /etc/chef/node.json
